### ISSUE TITLE
Jumps from 0.1.1 to 0.2.1 instead of 0.2.0

### ISSUE THREAD

**Issue by eturino** [VincenzoManto/light-release#4]
Current state: version 0.1.1. 

After having a new `feat` commit, instead of jumping to 0.2.0, it goes to 0.2.1. 

Expected: Whenever it jumps a major, it should reset the patch and minor. Whenever it jumps a minor, it should reset the patch.

**Comment by eturino** [comment]
Might be interesting to have a look at https://github.com/denoland/std/blob/8c9b4c6972e7eed0214f810542168ab746a306be/semver/increment.ts and https://github.com/denoland/std/blob/8c9b4c6972e7eed0214f810542168ab746a306be/semver/increment_test.ts for an implementation and test suite of all the possibilities. My guess is that you still don't want to include any dependency so recreating might be needed then.

**Comment by VincenzoManto** [comment]
Hi @eturino, thank you for your suggestions! The version jump is intentional and configurable: to avoid it, you can set `"squashIntoSingleVersioning": true` in the `light-release.config.json`. I'll add some additional documentation to clarify this.

I also agree about adding some test suites and will review your references.

**Comment by eturino** [comment]
@VincenzoManto  `squashIntoSingleVersioning` was enabled and it was the one that didn't jump properly. It is fixed in my PR.

**Comment by VincenzoManto** [comment]
> Might be interesting to have a look at https://github.com/denoland/std/blob/8c9b4c6972e7eed0214f810542168ab746a306be/semver/increment.ts and https://github.com/denoland/std/blob/8c9b4c6972e7eed0214f810542168ab746a306be/semver/increment_test.ts for an implementation and test suite of all the possibilities. My guess is that you still don't want to include any dependency so recreating might be needed then.

Do you refer just to those 2 test files?

**Comment by eturino** [comment]
The test file particularly to base the test suite of this implementation on all the examples, etc.
